# BLOG CONFIGURATION
post_navigation: true
paginate: 10
paginate_path: "blog/page:num"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]

title: Stock Market Prediction        # Name of website
# avatar: assets/img/avatar.png         # Path of avatar image, to be displayed in the theme's header
description: Stock Market Prediction          # Short description, primarily used by search engines
# favicon: assets/favicon.ico           # Icon displayed in the tab
color_theme: auto                     # color theme auto, dark or light


header_text: Stock Market Predictor
footer_text: Copyright 2023
header_feature_image: https://www.thestreet.com/.image/ar_4:3%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTY3NTM5MzU2NjcwNTY4MzM0/best-and-worst-closed-end-funds.jpg" alt="stockmovementimg
header_feature_image_responsive: true
