theme: jekyll-theme-cayman
title: Stock Market Prediction with LSTM Neural Network
description: Prediction for Next 7 days with recommended actions and expected gains/losses, accomplished 8% gains over 7-day transaction at most
