# BLOG CONFIGURATION
post_navigation: true
paginate: 10
paginate_path: "blog/page:num"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]

title: Stock Market Prediction        # Name of website
# avatar: assets/img/avatar.png         # Path of avatar image, to be displayed in the theme's header
description: Stock Market Prediction          # Short description, primarily used by search engines
# favicon: assets/favicon.ico           # Icon displayed in the tab
color_theme: auto                     # color theme auto, dark or light


header_text: Stock Market Predictor
footer_text: Copyright 2023
header_feature_image: assets/img/header/my-header-image.png
header_feature_image_responsive: true
